config/routes.rb
MyMedia::Application.routes.draw do

  resources :media

  root :to => 'media#index'

 get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/image.rb
# == Schema Information
#
# Table name: media
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  description          :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  media_type           :integer
#  url                  :string(255)
#  content_file_name    :string(255)
#  content_content_type :string(255)
#  content_file_size    :integer
#  content_updated_at   :datetime
#

class Image < Media
	
end

app/models/media.rb
# == Schema Information
#
# Table name: media
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  description          :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  media_type           :integer
#  url                  :string(255)
#  content_file_name    :string(255)
#  content_content_type :string(255)
#  content_file_size    :integer
#  content_updated_at   :datetime
#

require 'elasticsearch/model'


class Media < ActiveRecord::Base
  attr_accessible :description, :name, :url, :content, :public, :media_type
  
  belongs_to :user
  validates :name, :description, presence: true
  validates_inclusion_of :media_type, :in => [0, 1]
  validates :url, presence: true, :if => Proc.new {|media| media.media_type == 1}
  validates :content, presence: true, :if => Proc.new {|media| media.media_type ==0}

  has_attached_file :content
  validates_attachment_content_type :content, :content_type => /\Aimage/
  validates_attachment_file_name :content, :matches => [/png\Z/, /jpe?g\Z/]
  do_not_validate_attachment_file_type :content

  scope :videos, where(media_type: 1)
  scope :images, where(media_type: 0)
  scope :public, where(public: true)

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json(options={})
    as_json(
      only: [:id, :name, :description]
    )
  end

  module Type
  	Video = 1
  	Image = 0
  end

  def is_image?
  	self.media_type == Type::Image
  end

  def is_video?
  	self.media_type == Type::Video
  end

  def video_id
  	self.url.split("=").last
  end
end

Media.import

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  has_many :medias
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  
  require 'will_paginate/array'
  before_filter :media_type, [:new]

  def index 
    @media = current_user.present? ? Media.where("user_id = ? or public = ?", current_user.id, true) : Media.where(public: true)
    @media = @media.videos if @media_type == Media::Type::Video
    @media = @media.images if @media_type == Media::Type::Image
    if params[:search]
      @media = @media.search(params[:search]).records.paginate(page: params[:page], per_page: 20)
    else
      @media = @media.paginate(page: params[:page], per_page: 20)
    end
  end

  def show
    @media = Media.find_by_id(params[:id])
  end

  def new
    @medium = current_user.medias.new()
  end

  def create
    @medium = current_user.medias.new(params[:media])
    if @medium && @medium.save
      redirect_to medium_path(@medium.id)
    else
      render 'new'
    end
  end

  def edit
    @medium = Media.find_by_id(params[:id])
  end

  def update
    @medium = Media.find_by_id(params[:id])
    if @medium && @medium.update_attributes(params[:media])
      redirect_to medium_path(@medium.id)
    else
      render 'edit'
    end
  end

  def destroy
    Media.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def media_type
    @media_type = params[:media_type].to_i if params[:media_type].present?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMedia</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to MyMedia, media_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Add New Media", new_medium_path%></li>
         <% else %>
         <li> <%= link_to "Login To Create Media", "/auth/google_oauth2", id: "sign_in" %></li>
          <% end %>
        <li><%= link_to "Image", media_path(:media_type => Media::Type::Image) %></li> 
      </ul>
      <%= form_tag media_path, :method => 'get', class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: "form-control" %>
         </div>
        <%= submit_tag "Search", :name => nil , class: "btn btn-default" %>
       <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Video", media_path(:media_type => Media::Type::Video) %></li>
        <% unless current_user %>
          <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
        <% end %>
        <% if current_user %>
          <li> <%= link_to "Signed in as #{current_user.name}!", "#" %></li>
          <li> <%= link_to "Sign out", signout_path, id: "sign_out" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/media/_form.html.erb
<div class="row-fluid">
  <div class="col-sm-3"></div>
  <div class= "col-sm-6">
    <%= form_for @medium, :url => url_for(:action => action), html: {class: "form-horizontal"} do |f| %>
      <% @medium.errors.full_messages.each do |msg| %>
      <li style="color: red"><%= msg %></li>
   <% end %>
      <div class="control-group">
        <% unless @medium.id.present? %>
          <%= f.radio_button(:media_type, 0) %>
          <%= f.label(:media_type_0, "Image") %>
          <%= f.radio_button(:media_type, 1) %>
          <%= f.label(:media_type_1, "Video") %>
        <% end %>
      </div>
      <div class="control-group">
      <%= f.label :name, class: 'control-label'%>
      <div class='controls'>
      <%= f.text_field :name ,required: true%>
      </div>
      </div>
      <div class="control-group">
        <%= f.label :description, class: 'control-label'%>
        <div class='controls'>
        <%= f.text_field :description, required: true, class: 'controls' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :make_it_public, class: 'control-label'%>
        <div class='controls'>
        <%= f.check_box :public, checked_value: true, unchecked_value: false, class: 'controls' %>
        </div>
      </div>
      <div id="show_url"> 
        <div class="control-group">
          <%= f.label :url, class: 'control-label'%>
          <div class='controls'>
          <%= f.text_field :url, class: 'controls'%>
          </div>
        </div>
      </div>
      <div id="show_content">
        <div class="control-group">
        <%= f.label :upload_image, class: 'control-label'%>
        <%= f.file_field :content, class: 'controls'%>
        </div>
      </div>
      <div class="form-actions">
          <%= f.submit :class => "btn btn-primary has-above" %>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_tag do %>
  jQuery(document).ready(function(){
    Media.init("<%= @medium.media_type.nil?%>", "<%= @medium.media_type%>");
    jQuery("#media_media_type_1").on("change", function(){
      jQuery("#show_url").show();
      jQuery("#show_content").hide();
    });
    jQuery("#media_media_type_0").on("change", function(){
      jQuery("#show_content").show();
      jQuery("#show_url").hide();
    });
  });
<% end %>

app/views/media/_image.html.erb
<div class = "col-mx-6 has-above-15">
  <div><strong> Name: <%= link_to image.name, medium_path(image) %></strong></div>
  <div><strong> Description: <%= image.description %></strong></div>
  <%= link_to image_tag(image.content.url), medium_path(image), height: 200, width: 150 %>
</div>

app/views/media/_search.html.erb
<%= form_tag media_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/media/_video.html.erb
<div class = "col-mx-6 has-above-15">
  <div><strong> Name: <%= link_to video.name, medium_path(video)%></strong></div>
  <div><strong> Description: <%= video.description %></strong></div>
  <iframe width="300" height="200" src="<%= "http://www.youtube.com/embed/#{video.video_id}" %>"></iframe>
</div>

app/views/media/edit.html.erb
<%= render partial: "form", :locals => {action: "update"} %>

app/views/media/index.html.erb
<div class="row-fluid">
	<div class ="col-sm-12"></div>
		<div class ="col-sm-3"></div>
		<div class ="col-sm-6">
			<% @media.each do |media|%>
			  <%= render partial: 'image', :locals => {image: media} if media.is_image? %>
			  <%= render partial: 'video', :locals => {video: media} if media.is_video? %>
			<% end %>
			<%= will_paginate @media %>
		</div>
		<div class ="col-sm-3"></div>
	</div>
</div>


<%= javascript_tag do %>
	jQuery("#search").val("");
<% end %>

app/views/media/new.html.erb
<%= render partial: "form", locals: {action: "create"}%>

app/views/media/show.html.erb
<div class="row-fluid">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
     <div><strong> Name: <%= @media.name %></strong></div>
     <div><strong>Description: <%= @media.description %></strong></div>
     <div>
	     <% if @media.is_video? %>
	     <iframe width="400" height="300" src="<%= "http://www.youtube.com/embed/#{@media.video_id}" %>"></iframe>
	     <% end %>
	     <% if @media.is_image? %>
	     <%= image_tag @media.content.url %>
	     <% end %>
	  </div>
  </div>
  <div class="col-sm-3">
    <% if @media.user == current_user %>  
	    <div class="col-sm-3">
		    <%= button_to "edit", edit_medium_path(@media), method: :get, class: "btn btn-primary" %>
		  </div>
		  <div class="col-sm-3">
		    <%= button_to "delete", medium_path, method: :delete, class: "btn btn-primary" %>
		  </div>
    <% end %>
	</div>
</div>